version: "3.7"
services:
  app:
    build:
      args:
        user: guest
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: iantheloop
    container_name: iantheloop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 6001:6001
      - 8080:8080
    environment:
      - CHOKIDAR_USER_POLLING=true
    networks:
      - iantheloop

  db:
    image: mysql:8.0
    container_name: iantheloop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - iantheloop

  nginx:
    image: nginx:alpine
    container_name: iantheloop-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - iantheloop

networks:
  iantheloop:
    driver: bridge
